"""Añadir columnas de fecha a Cotizacion

Revision ID: 652bfcf14452
Revises: 
Create Date: 2025-07-16 22:58:43.422022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652bfcf14452'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        # Le decimos que la columna no puede ser nula (nullable=False)
        # Y le damos un valor por defecto A NIVEL DE SERVIDOR (server_default)
        # para todas las filas que ya existen.
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.add_column(sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###
