"""Añadir tabla Plan y campos de seleccion a Cotizacion

Revision ID: 8ba74af6844f
Revises: 
Create Date: 2025-07-27 16:42:22.869722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba74af6844f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('aseguradora', sa.String(length=100), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('tipo_seguro', sa.String(length=50), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fechaNacimiento', sa.String(length=20), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('cedula', sa.String(length=10), nullable=True),
    sa.Column('provincia', sa.String(length=50), nullable=True),
    sa.Column('canton', sa.String(length=50), nullable=True),
    sa.Column('parroquia', sa.String(length=100), nullable=True),
    sa.Column('callePrincipal', sa.String(length=150), nullable=True),
    sa.Column('calleSecundaria', sa.String(length=150), nullable=True),
    sa.Column('numeroCasa', sa.String(length=20), nullable=True),
    sa.Column('referencias', sa.String(length=255), nullable=True),
    sa.Column('tipoSeguroPrincipal', sa.String(length=50), nullable=True),
    sa.Column('tipoSeguroSalud', sa.String(length=50), nullable=True),
    sa.Column('tipoSeguroVida', sa.String(length=50), nullable=True),
    sa.Column('tipoSeguroAuto', sa.String(length=50), nullable=True),
    sa.Column('ocupacion', sa.String(length=100), nullable=True),
    sa.Column('marcaVehiculo', sa.String(length=50), nullable=True),
    sa.Column('modeloVehiculo', sa.String(length=50), nullable=True),
    sa.Column('anioVehiculo', sa.Integer(), nullable=True),
    sa.Column('placaVehiculo', sa.String(length=10), nullable=True),
    sa.Column('plan_seleccionado_id', sa.Integer(), nullable=True),
    sa.Column('precio_final', sa.Float(), nullable=True),
    sa.Column('aceptaTerminos', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_seleccionado_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cotizacion')
    op.drop_table('plan')
    # ### end Alembic commands ###
